### ISSUE TITLE
Some sanitizer names will break the bundle

### ISSUE THREAD

**Issue by stof** [tgalopin/html-sanitizer-bundle#11]
Sanitizer services are currently registered as `'html_sanitizer.'.$name` in the container. But this means that some values of `$name` can make it override the other services of the bundle, leading to unexpected behavior.

It would be better to name the services `'html_sanitizer.sanitizer.'.$name`, avoiding any clash with other services (this is a common mistake in bundles allowing to define a list of services with a configurable name suffix).
But that change would be a BC break for anyone referencing the service directly, so it would require bumping to 2.0.

**Comment by stof** [comment]
However, the Packagist download stats are telling me that only 1.1.0 gets some installs, which is the version locked in the symfony-demo currently. So it is probably not a big deal to bump to 2.0. The migration should be easy enough for users.

**Comment by tgalopin** [comment]
Closing, but we'll avoid this problem in the Symfony component.
