### ISSUE TITLE
You have requested a non-existent sanitizer extension "basic" (available extensions: )

### ISSUE THREAD

**Issue by codegain** [tgalopin/html-sanitizer-bundle#16]
Hi,
I'm getting the error `You have requested a non-existent sanitizer extension "basic" (available extensions: )`

My use case is that I try to decorate the Symfony translator:

services.yaml:
```
    app.translator.sanitizer:
        class:     App\Translation\SanitizerTranslator
        decorates: translator
        arguments:
            - '@app.translator.sanitizer.inner'
            - '@html_sanitizer.translations'
```

html_sanitizer.yaml:
```
html_sanitizer:
    sanitizers:
        translations:
            extensions: ['basic']
```

It only works if I set `extensions` to `[]` in the html_sanitizer.yaml. I also created a command where the my custom sanitizer works:

```
    App\Command\TranslationsCommand:
        arguments:
            $sanitizer: '@html_sanitizer.translations'
```

Any idea why this does not work on my translator decorator?

**Comment by tgalopin** [comment]
Closing as old, if you still has the issue ping me here and I'll have a look.
