### ISSUE TITLE
Compatibility for Symfony ^4.2.5

### ISSUE THREAD

**Issue by cybernet** [tgalopin/html-sanitizer-bundle#7]
As of 4.2.5 symfony started to throw this deprecation

`Not implementing the static getExtendedTypes() method in HtmlSanitizer\Bundle\Form\TextTypeExtension when implementing the Symfony\Component\Form\FormTypeExtensionInterface is deprecated since Symfony 4.2. The method will be added to the interface in 5.0.` 

Can this be fixed in the next release ?

**Comment by stof** [comment]
Already fixed in https://github.com/tgalopin/html-sanitizer-bundle/commit/aabcda7bdc2bc55322ffe4f36bb7d839a5c3e727 (but not released yet)

**Comment by tgalopin** [comment]
Let's release :) .
