### ISSUE TITLE
Better registry API

### ISSUE THREAD

**Issue by stof** [tgalopin/html-sanitizer-bundle#8]
Currently, the recommendation for the registry is to inject a Symfony service locator, typehinting the PSR ContainerInterface. But that does not help with autowiring.
The handling of a default sanitizer is also not handled by the registry, forcing all places using the registry to also inject the name of the default sanitizer (look at the form type extension and the twig extension for instance).

A solution could be to implement a dedicated SanitizerRegistry, with a `get(string $name = null): SanitizerInterface` method (which will also help static analysis of code using the registry btw), which would deal with the ServiceLocator and the default name internally.
And this SanitizerRegistry could be exposed to autowiring.

**Comment by tgalopin** [comment]
Seems a good idea, thanks for the feedback. I'll keep it in mind (don't hesitate to tell me if you want to do the PR :) ).
